#!/bin/bash
# modified from http://rboci.blogspot.com/2012/10/command-line-xslt-20.html

set -e

XSL=`readlink -f "$1"`
XML=`readlink -f "$2"`

# get the absolute path of the executable even if a symlink was used
DIR="$(dirname "$(readlink -f "$0")")"

if ! [ -f "$XSL" ]; then
   echo stylesheet does not exist
   exit 1
fi

if ! [ -d "$DIR"/target ]; then
   mvn package -f "$DIR"
fi

if [ -f "$XML" ]; then
   java -jar "$DIR"/target/xsltprocJ-1.0-SNAPSHOT-jar-with-dependencies.jar -s:"$XML" -xsl:"$XSL"
else
   echo no file to transform
   exit 1
fi
